app = "vix-bot"
primary_region = "cdg"

[env]
BOT_TOKEN = "7660218441:AAFcJJwueHWpeZKvwzKX5CQKg8Qjz57P250"
TMDB_API_KEY = "be78689897669066bef6906e501b0e10"
RESOLVER_URL = "https://vix-resolver.fly.dev"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
